insert into planet values(1,'A','Earth');
insert into planet values(2,'B','Moon');
insert into planet values(3,'C','Jupiter');
insert into planet values(4,'D','Venus');
insert into planet values(5,'E','Mars');
insert into planet values(6,'F','Saturn');
insert into planet values(7,'G','Uranus');
insert into planet values(8,'H','Pluto');
insert into planet values(9,'I','Neptune');
insert into planet values(10,'J','Mercury');
insert into planet values(11,'K','Alpha Centauri');
insert into planet values(12,'L','Luhman 16');
insert into planet values(13,'M','Epsilon Eridani');
insert into planet values(14,'N','Groombridge 34');
insert into planet values(15,'O','Epsilon Indi');
insert into planet values(16,'P','Tau Ceti');
insert into planet values(17,'Q','Kapteyn star');
insert into planet values(18,'R','Gliese 687');
insert into planet values(19,'S','Gliese 674');
insert into planet values(20,'T','Gliese 876#');
insert into planet values(21,'U','Gliese 832');
insert into planet values(22,'V','Fomalhaut');
insert into planet values(23,'W','Virginis');
insert into planet values(24,'X','HD 102365');
insert into planet values(25,'Y','Gliese 176');
insert into planet values(26,'Z','Gliese 436');
insert into planet values(27,'A-','Pollux');
insert into planet values(28,'B-','Gliese 86');
insert into planet values(29,'C-','HIP 57050');
insert into planet values(30,'D-','Piscium');
insert into planet values(31,'E-','GJ 1214');
insert into planet values(32,'F-','Upsilon Andromedae');
insert into planet values(33,'G-','Gamma Cephei');
insert into planet values(34,'H-','HD 176051');
insert into planet values(35,'I-','Gliese 317');
insert into planet values(36,'J-','HD 38858');
insert into planet values(37,'K-','Ursae Majoris');

insert into route values(1,'B',0.44,'A');
insert into route values(2,'C',1.89,'A');
insert into route values(3,'D',0.10,'A');
insert into route values(4,'H',2.44,'B');
insert into route values(5,'E',3.45,'B');
insert into route values(6,'F',0.49,'C');
insert into route values(7,'L',2.34,'D');
insert into route values(8,'M',2.61,'D');
insert into route values(9,'G',3.71,'H');
insert into route values(10,'I',8.09,'E');
insert into route values(11,'J',5.46,'F');
insert into route values(12,'K',3.67,'F');
insert into route values(13,'Z',5.25,'G');
insert into route values(14,'Z',13.97,'I');
insert into route values(15,'J',14.78,'I');
insert into route values(16,'T',15.23,'L');
insert into route values(17,'N',10.43,'T');
insert into route values(18,'S',14.22,'T');
insert into route values(19,'O',6.02,'S');
insert into route values(20,'U',5.26,'O');
insert into route values(21,'R',12.34,'J');
insert into route values(22,'P',10.10,'R');
insert into route values(23,'L-',9.95,'R');
insert into route values(24,'Y',18.91,'Z');
insert into route values(25,'Q',22.04,'Y');
insert into route values(26,'X',10.51,'Q');
insert into route values(27,'X',23.61,'L-');
insert into route values(28,'K-',19.94,'X');
insert into route values(29,'U',9.31,'P');
insert into route values(30,'K-',21.23,'U');
insert into route values(31,'J-',25.96,'U');
insert into route values(32, 'V',3.16,'J');
insert into route values(33,'V',20.42,'K-');
insert into route values(34,'I-',17.10,'J-');
insert into route values(35,'A-',19.52,'Y');
insert into route values(36,'B-',31.56,'A-');
insert into route values(37,'C-',23.13,'B-');
insert into route values(38,'W',28.89,'K-');
insert into route values(39,'C-',10.64,'W');
insert into route values(40,'E-',36.19,'W-');
insert into route values(41,'D-',36.48,'C-');
insert into route values(42,'E-',41.26,'E-');
insert into route values(43,'F-',42.07,'E-');
insert into route values(44,'G-',17.63,'F-');
insert into route values(45,'H-',40.48,'G-');

insert into traffic values(3,'A',0.10,'D');
